version: "3"
services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles # --quiet
    environment:
          - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000:3000"
      - "9000:9000"
      - "9229:9229"
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules