version: "3"
services:


  redis:
    image: redis
    expose:
        - "6379"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles # --quiet
    environment:
          - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000:3000"
      - "9000:9000"
      - "9229:9229"
      - "80:80"
      - "843:843"
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules


  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    environment:
        - NODE_ENV=development
        - PORT=3000
        - REDIS_URL=redis://redis
    command: "sh -c 'npm i && npm run worker'"
    volumes:
        - .:/var/www/app
    links:
        - redis
